### ISSUE TITLE
 Option to display married name of females in chart.

### ISSUE THREAD

**Issue by zeezhao** [magicsunday/webtrees-descendants-chart#38]
**Is your feature request related to a problem? Please describe.**
Sometimes, there is a need to show the married name of females in the chart, instead of birth name.

**Describe the solution you'd like**
It would be nice to have an option for instance in the "Show more options" section for "Display Married Names". Thanks

**Comment by magicsunday** [comment]
Fixed in https://github.com/magicsunday/webtrees-descendants-chart/releases/tag/1.5.0

**Comment by zeezhao** [comment]
Hi - still not working for me. Please see:
https://github.com/magicsunday/webtrees-descendants-chart/issues/39#issuecomment-1689998739

edit:
I also did a quick test with "Show married names.", and it did not seem to work. Note that I recently fixed married names to use correct GED format, instead of the special field webtrees was using.

**Comment by magicsunday** [comment]
1.5.0 was corrupt, 1.5.1 should work now. 

If it still not working, please provide me a working sample gedcom. In my tree I see the spouses with the married name (2 TYPE married).

**Comment by zeezhao** [comment]
Thanks. I did try it in 1.5.1 and same issue.
Unfortunately, I can't export the gedom but it is definitely using married name (2 TYPE married). Looking at raw gedcom, it is like:
<code>
1 NAME XXX /YYY/
....
1 NAME XXX /ZZZ/
2 TYPE MARRIED
</code>
But it displays "XXX YYY" always. Please is it possible the version you released is not taking into the account the flag? It gives me the same result whether "Show married names." is ticked or not.

**Comment by magicsunday** [comment]
- What type is the first name of the person?

Webtrees displays the first name from the gedcom as the primary name (except there is a different name matching the current locale):
```
// Generally, the first name is the primary one....
$this->getPrimaryName = 0;
// ...except when the language/name use different character sets
...
```

Without sample data, I can't reproduce your problem.

In my chart it's working as expected:
- Default:
![grafik](https://github.com/magicsunday/webtrees-descendants-chart/assets/564393/0307f26a-9a95-476a-a630-1547bb90bc7b)
- Show married name
![grafik](https://github.com/magicsunday/webtrees-descendants-chart/assets/564393/2a8454f1-743c-4f71-8cae-94eebf66a4ea)

**Comment by zeezhao** [comment]
Thanks for your help. The name type is "birth name". 
edit: In my example, she is the descendant, so she is shown on top, so opposite to your example above. Her husband is show below.

**Comment by magicsunday** [comment]
Could you please check, if https://github.com/magicsunday/webtrees-descendants-chart/commit/b288b756bde674fd96f9fd9801c9a83a10d59fa7 fixes your problem?

**Comment by zeezhao** [comment]
Thank you - this seems to work too! I will do more testing to confirm.

**Comment by zeezhao** [comment]
This looks fine now. Thank you for your swift response and hard work!
