### ISSUE TITLE
Option to plot descendants children ordered by age, when spouse hidden

### ISSUE THREAD

**Issue by zeezhao** [magicsunday/webtrees-descendants-chart#39]
**Is your feature request related to a problem? Please describe.**
Again, thanks for this great module! 

In some instances for a polygamous family, there is the need to display the children of a parent by age seniority. For instance, lets say a father has 2 wives (W1, W2) and each wife has 2 children:

- W1 has C1, C3.
- W2 has C2 ,C4. 
- Where age of C1>C2>C3>C4
- If "Hide the spouses associated with an individual" option is selected from the chart, I want to show children order as: C1, C2, C3, C4 instead of C1, C3, C2, C4

**Describe the solution you'd like**
If "Hide the spouses associated with an individual" option is selected from the chart, then also have an option to order children by Age. 

If no Age entered, then just the current default sorting for display.

Another solution may be the ability to manually reorder the children displayed. But I imagine this may be more complicated.
Thank you.

**Comment by magicsunday** [comment]
Hello. Thanks for the hint. This appears to be a bug introduced by the customization to display spouses. In general, the children should be sorted by birth date if no spouses are displayed.

**Comment by zeezhao** [comment]
Hello @magicsunday - Thank you for the feedback. Please do you know if this is a quick fix, or it will require more time?

**Comment by magicsunday** [comment]
Hi @zeezhao,

I think I fixed it. I created a new release version. Please check it out here: https://github.com/magicsunday/webtrees-descendants-chart/releases/tag/1.4.1

**Comment by zeezhao** [comment]
Thanks for your new release!

I had a quick look, and I found that:

- For the case I mentioned above for W1 & W2, it is still showing:  C1, C3, C2, C4, whereas I want C1, C2, C3, C4
- Also, in some cases where some birthdates are not filled because not known, it is better to maintain the existing order. I think a condition of: if and only if all birthdays are filled, do the new sorting by age. If not default to the existing sorting.

Thanks for your help

**Comment by magicsunday** [comment]
You are right. Its not fixed. I will have to take a deeper look.

**Comment by magicsunday** [comment]
Seems to fit now:

![grafik](https://github.com/magicsunday/webtrees-descendants-chart/assets/564393/3d0d39d0-2687-4293-879b-e204041af204)
![grafik](https://github.com/magicsunday/webtrees-descendants-chart/assets/564393/078000f1-dafb-422a-a345-b0b19b08d9be)

Check out release 1.4.2

**Comment by zeezhao** [comment]
Thanks for your quick turnaround - much appreaciated!

I did a quick test and it seems to work when every date is set in a tree. However because some records can not be fixed, please here are my observations:

1. When birthdates are not set in some branches because unknown, the order appears random. Please is it possible retain the original order of the children, as set up in webtrees? So if any date in a branch-level is not set, then default to original order. [Using above example, if for instance C1 or C2 or C3 or C4 birthdate is not stated, then just display as C1, C3, C2, C4 as normal]
2. When privacy is set to hide birth i.e. "Hide from everyone", the order again seems random. I imagine birthdate cannot be used in this instance, so please is it possible retain the original order of the children as set up in webtrees? This is necessary, as for some printing there is a need to hide birthdates. [Using above example, if birthdates cant be read at all, then just display as C1, C3, C2, C4 as normal]
3. In summary, the default should be: if any birthdate in a branch at a level is not set, then default to original order as set up in webtrees. [Using above example, if at least one birthdate not available at the level, then just display as C1, C3, C2, C4 as normal]

I suspect this may make the code more complicated. The main reason is some birthdates are not known and may never be known due age/no records...

Thanks for your help!

edit: added comments to clarify using earlier examples.

**Comment by magicsunday** [comment]
Btw. webtrees also seems not to handle polygamous families the right way:
![grafik](https://github.com/magicsunday/webtrees-descendants-chart/assets/564393/cf727a88-6d89-4dfc-ae6e-e9f15b674d04)

**Comment by zeezhao** [comment]
Thanks for your reply.

I don't use the "Family Book" module at all. 

In my opinion, your "webtrees-descendants-chart" module is excellent, in terms of functionality, presentation, download ability, etc. This is the only add-on module I use, and I occasionally use "topola" too. Everything else I use is just for data entry. So for me, your module is what makes webtrees as a whole great!

In my using webtrees own "Descendants" chart, it shows it correctly under each wife, provided you have set up a spouse for each person, which I normally do even if it is a "dummy". My use case is 1 male to a few females.  The webtrees descendants chart does not have ability to "hide spouses" anyway. I am using v2.1.17.

edit:
Fixed typos, etc

**Comment by magicsunday** [comment]
Fixed in https://github.com/magicsunday/webtrees-descendants-chart/releases/tag/1.5.0

**Comment by zeezhao** [comment]
Hi - Thanks for the latest release.

- When the "Hide the spouses associated with an individual. " is Not ticked, the chart is blank.
- The date condition should please be applied to Marriage date too i.e.  if any marriage date in a branch at a level is not set, then default to original family order as set up in webtrees. Right now, v1.5.0 is causing a random order of families for me, since marriage date is not necessarily know. I believe it was same in previous version too.
- I also did a quick test with "Show married names.", and it did not seem to work. Note that I recently fixed married names to use correct GED format, instead of the special on webtrees was using.
- Children also still appears random when date not set. Please preserve original order in this instance.

Thanks for your help. Much appreciated.
